version: 2
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: apk add build-base luarocks5.3 lua5.3http
      - run: alias lua=lua5.3 luarocks=luarocks5.3
      - run: luarocks install busted && luarocks install penlight
      - run: luarocks make
      - run: busted --run=ci